name: Lint And Format Fixes
on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    #    runs-on: [self-hosted, linux, x64]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: 'write'
      id-token: 'write'
      pull-requests: 'write'
      checks: 'read'
    steps:
    - name: Install Go
      uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6
      with:
        go-version: latest
    - name: Clone Repository (Latest)
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      if: github.event.inputs.git-ref == ''
      with:
        persist-credentials: false
    - name: Clone Repository (Custom Ref)
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      if: ${{ github.event.inputs.git-ref != '' &&  github.event.inputs.git-ref != 'main' && github.event.inputs.git-ref != 'master' }}
      with:
        ref: ${{ github.event.inputs.git-ref }}
        persist-credentials: false
    - name: pin actions and fmt action yaml
      run: "./.github/scripts/lintfix-pin-actions.sh"
    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest
    - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5
    - name: install dependencies
      run: |
        pip install --user mdformat mdformat-gfm mdformat-shfmt mdformat-tables mdformat-toc
        # linkify-it-py needed rust so I skipped it
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6
    - name: Format Markdown
      run: "./.github/scripts/lintfix-fmt-md.sh"
    - name: Commit and push changes (if any)
      shell: bash
      env:
        CI_COMMIT_MESSAGE: update profile readme with latest posts
        CI_COMMIT_AUTHOR: github-actions[bot]
        CI_COMMIT_EMAIL: username@users.noreply.github.com
      run: ""
